// API key has not been given, to get an OPEN API API key, go to the website to purchase it

export const OPEN_API_KEY= ""



export const USER_PROMPTS1= ["What is the email address of the employee who is the Sales Manager?",
                            "Which employee in the company works in the Product Development department?",
                            "Who are the employees working in the 'Finance' department?",
                            "Retrieve the total number of meetings attended by 'Na Li' in her weekly updates?",
                            "Which employees worked more than 40 hours during week 1?",
                            "How many employees does the company have in total?",
                            "What is the average hours worked by all employees during week 2?",
                            "How much total sales revenue has the Sales department generated to date?",
                            "What is the total sales revenue generated by the company during week 1?",
                            "Which employee attended the most meetings during week 2?",
                            "List all employees who work in the IT department within the company?",
                            "Compare the hours worked by 'Wei Zhang' and 'Tao Huang' during week 1?",
                            "What is the total number of hours worked and average sales revenue for employees in the Business Development department?"
                            ]

export const USER_PROMPTS2= ["What is the email address of the employee who is the Sales Manager?",
                            "Which employee in the company works in the Product Development department?",
                            "What was the sales revenue of 'Wei Zhang' for the week starting on \'2024-08-28\'?",
                            "Who are the employees working in the 'Finance' department?",
                            "Retrieve the total number of meetings attended by 'Na Li' in her weekly updates?",
                            "Which employees worked more than 40 hours during week 1?",
                            "How many employees does the company have in total?",
                            "What is the average hours worked by all employees during week 2?",
                            "How much total sales revenue has the Sales department generated to date?",
                            "What is the total sales revenue generated by the company during week 1?",
                            "Who worked the most hours during the first week of September 2024?",
                            "Which employee attended the most meetings during week 2?",
                            "Which employees in the company were hired during a time of industry recession?",
                            "Who are the employees that faced challenges with customer retention, and what solutions did they propose?",
                            "Which employees work in roles that likely require data analysis or reporting skills (based on job titles)?",
                            "List all employees who work in the IT department within the company?",
                            "Compare the hours worked by 'Wei Zhang' and 'Tao Huang' during week 1?",
                            "Who are the top 3 employees by total hours worked during the last 4 weeks?",
                            "Who achieved the highest sales revenue in a single week, and when?",
                            "What is the total number of hours worked and average sales revenue for employees in the Business Development department?"
                            ]

export const LLM_PROMPT=`With the SQL table of:
                -- Employee table (basic info)
                CREATE TABLE employees (
                    Employee_ID INT PRIMARY KEY,
                    Name VARCHAR(20),
                    Department VARCHAR(20),
                    Hire_Date TIMESTAMP,
                    Email_Address VARCHAR(50),
                    Job_Title VARCHAR(50)
                );

                -- EmployeeWeeks table (employee-specific weekly data)
                CREATE TABLE employee_weeks (
                    Employee_ID INT,
                    Week_Num INT CHECK (Week_Num BETWEEN 1 AND 10),
                    Num_Meets INT,
                    Total_Sales DECIMAL(10,2),
                    Hours_Worked INT,
                    Activities VARCHAR(50),

                    PRIMARY KEY (Employee_ID, Week_Num),  -- Composite key
                    FOREIGN KEY (Employee_ID) REFERENCES employees(Employee_ID)
                );

                , generate SQL commands only that correspond by question given by the user, return as a the SQL command only with no line breaks and no SQL label`

